config/routes.rb
Rails.application.routes.draw do
    
    root  'sessions#new'

    # Groups
    get '/groups/new'      => 'groups#new',  :as => "groups_new"
    get '/groups/:id/edit' => 'groups#edit', :as => "groups_edit"

    get    '/groups'     => 'groups#index',   :as => "groups_index"
    post   '/groups'     => 'groups#create',  :as => "groups_create"
    get    '/groups/:id' => 'groups#show',    :as => "groups_show"
    patch  '/groups/:id' => 'groups#update',  :as => "groups_update"
    delete '/groups/:id' => 'groups#destroy', :as => "groups_destroy"

    get    '/groups/:id/:page' => 'groups#show',    :as => "groups_show_page"

    # Users
    get '/users/new'      => 'users#new',  :as => "users_new"
    get '/users/:id/edit' => 'users#edit', :as => "users_edit"

    post   '/users'     => 'users#create',  :as => "users_create"
    get    '/users/:id' => 'users#show',    :as => "users_show"
    patch  '/users/:id' => 'users#update',  :as => "users_update"
    delete '/users/:id' => 'users#destroy', :as => "users_destroy"

    # Sessions
    get  '/login'      => 'sessions#new',     :as => "sessions_new"
    post '/sessions'   => 'sessions#create',  :as => "sessions_create"
    delete '/sessions' => 'sessions#destroy', :as => "sessions_destroy"

    # Posts
    post '/posts/:id' => 'posts#create', :as => "posts_create"

    # Photos
    post '/photos/:id' => 'photos#create', :as => "photos_create"
    get  '/photos/:id' => 'photos#show',   :as => "photos_show"

    # Comments
    post '/comments/:id' => 'comments#create', :as => "comments_create"

end

app/models/group.rb
class Group < ActiveRecord::Base

    has_many :group_members
    has_many :users, :through => :group_members
    has_many :posts, :through => :group_members
    has_many :photos, :through => :group_members

    validates_presence_of :name

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    before_action :require_user
    before_action :require_group, :only => [:show, :edit, :update, :destroy]
    before_action :require_member, :only => [:show, :edit, :update, :destroy]
    before_action :require_admin, :only => [:edit, :update, :destroy]

    def require_user
        if session[:user_id].blank?
            redirect_to sessions_new_url, notice: "You must be logged in to do that."
            return
        end
        @user = User.find_by(id: session[:user_id])
        if not @user
            session.delete(:user_id)
            redirect_to sessions_new_url, notice: "Not a valid user."
        end
    end

    def require_group
        @group = Group.find_by(id: params['id'])
        if not @group
            redirect_to groups_index_url, notice: "Not a valid group."
        end
    end

    def require_member
        @member = GroupMember.find_by(user_id: @user.id, group_id: @group.id)
        if not @member
            redirect_to groups_index_url, notice: "You are not a member of that group"
        end
    end

    def admin_status
        return GroupMember.find_by(user_id: @user.id, group_id: @group.id).admin
    end

    def require_admin
        if not admin_status
            redirect_to groups_index_url, notice: "You must be an admin to do that."
        end
    end

    def index
        @groups = @user.groups.limit(100)
    end

    def show
        @admin = admin_status
        @active_page = params[:page] ? params[:page] : "posts"
        @pages = ["posts", "photos", "members", "info"]
        @posts = @group.posts.order(time_posted: :desc).limit(100)
        @photos = @group.photos.order(time_posted: :desc).limit(100)
        @photo_id = params[:photo_id]
    end

    def new
    end

    def create
        group = Group.new
        group.name = params[:name]
        group.description = params[:description]
        group.save

        member = GroupMember.new
        member.group_id = group.id
        member.user_id = @user.id
        member.admin = true
        member.save

        redirect_to groups_index_url
    end

    def edit
    end

    def update
        @group.name = params[:name]
        @group.description = params[:description]
        @group.save
        redirect_to groups_show_url(@group.id)
    end

    def destroy
        @group.delete
        redirect_to groups_index_url
    end
end

app/views/groups/_info.html.erb
<div class="panel-body"></div>
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title">
          Group Description
      </h3>
  </div>
  <div class="panel-body">
    <%= @group.description %>
  </div>
</div>

app/views/groups/_members.html.erb
<table class="table">
    <thead>
        <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Email</th>
        </tr>
    <thead>

    <% @group.users.each do |group| %>
        <tr>
            <td><%= group.last_name %></td>
            <td><%= group.first_name %></td>
            <td><%= group.email %></td>
        </tr>
    <% end %>
</table>

app/views/groups/_photos.html.erb
<div style="padding-top: 15px;"></div>
<div class="row">
<%= form_tag photos_create_url, multipart: true, :class => 'form-inline' do %>
    <div class="col-lg-6 col-sm-6 col-12">
        <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                    Browse&hellip; <%= file_field_tag 'picture' %>
            </span>
            </span>
            <input type="text" class="form-control" readonly>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-default">Upload</button>
        </div>
    </div>
<% end %>
</div>
<div style="padding-top: 15px;"></div>

<div>
<% @photos.each do |photo| %>
<!-- Button trigger modal -->
<a href="<%= groups_show_page_url(@group.id, "photos", :photo_id => photo.id) %>">
    <%= image_tag "/photos/#{photo.id}", :class => "img-thumbnail", :width => "140", :height => "140" %>
</a>

<!-- Modal -->
<div class="modal fade" id="image-modal-<%= photo.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">Photo posted by <%= photo.user.first_name %>
        <small>
            <div class="pull-right" style="padding-right: 10px;">
                <%= photo.time_posted.to_formatted_s(:long) %>
            </div>
        </small>
        </h4>
      </div>
      <div class="modal-body">
          <%= image_tag "/photos/#{photo.id}", :class => "img-responsive center-block" %>
          <hr sylte="margin-top: 0px; margin-bottom: 0px">
          <%= form_tag comments_create_url(photo.id), :class => 'form-inline' do %>
              <div class="input-group">
                  <input type=text" class="form-control" name="content" placeholder="Comment">
                  <span class="input-group-btn">
                      <button type=submit class="btn btn-primary">Post</button>
                  </span>
              </div>
          <% end %>
          <hr sylte="margin-top: 0px; margin-bottom: 0px">
          <% photo.comments.order(time_posted: :desc).limit(100).each do |comment| %>
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <h3 class="panel-title">
                          <%= comment.user.first_name + " " + comment.user.last_name %>
                          <small>
                              <div class="pull-right">
                                  <%= comment.time_posted.to_formatted_s(:long) %>
                              </div>
                          </small>
                      </h3>
                  </div>
                  <div class="panel-body">
                      <%= comment.content %>
                  </div>
              </div>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<% end %>
<div>
<% if @photo_id %>
    <script>
    $("#image-modal-<%= @photo_id %>").modal('show')
    </script>
<% end %>

app/views/groups/_posts.html.erb
<% if @post and @post.errors.any? %>
    <ul>
        <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<div class="panel-body"></div>
<%= form_tag posts_create_url(@group.id), :method => 'post', :class => 'form-horizontal' do %>
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title">
    <input type="text" class="form-control" name="title" placeholder="Title">
      </h3>
  </div>
  <div class="panel-body">
      <div style="margin-bottom: 15px">
    <textarea class="form-control" rows="3" name="content" placeholder="Content"></textarea>
      </div>
      <div>
    <button type="submit" class="btn btn-primary">Post</button>
      </div>
  </div>
</div>
<% end %>

<% @posts.each do |post| %>
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title">
          <%= post.title %>
          <small>
              <div class="pull-right">
                  <%= post.time_posted.to_formatted_s(:long) %>
              </div>
          </small>
      </h3>
  </div>
  <div class="panel-body">
      <%= post.content %>
  </div>
</div>
<% end %>

app/views/groups/edit.html.erb
<div>
<h2>Editing Group: <%= @group.name %>
</h2>

<%= form_tag groups_update_url(@group.id), :method => 'patch', :class => 'form-horizontal' do %>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-5">
        <input type="text" class="form-control" id="name" name="name" value="<%= @group.name %>">
    </div>
  </div>
  <div class="form-group">
    <label for="description" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-5">
        <textarea class="form-control" rows="3" id="description" name="description"><%= @group.description %></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Update</button>
    </div>
  </div>
<% end %>
</div>

app/views/groups/index.html.erb
<h1>Your Groups

<%= link_to "Create Group", groups_new_url, :class => 'btn btn-primary pull-right' %>
</h1>

<% if @groups.count != 0 %>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
        </tr>
    <thead>

    <% @groups.each do |group| %>
        <tr>
            <td><%= link_to group.name, groups_show_url(group.id) %></td>
            <td><%= group.description %></td>
        </tr>
    <% end %>
</table>
<% else %>
    <p>You are not a member of any groups.</p>
<% end %>

app/views/groups/new.html.erb
<h2>Create New Group</h2>
<%= form_tag groups_create_url, :method => 'post', :class => 'form-horizontal' do %>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-5">
        <input type="text" class="form-control" id="name" name="name">
    </div>
  </div>
  <div class="form-group">
    <label for="description" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-5">
        <textarea class="form-control" rows="3" id="description" name="description"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Create</button>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<div class="container">
<h1><%= @group.name %>

<% if @admin %>
<div class="dropdown pull-right">
    <a class="btn btn-default" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= groups_edit_url(@group.id) %>">Edit</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= groups_destroy_url(@group.id) %>" data-method='delete'>Delete</a></li>
    </ul>
</div>
<% end %>
</h1>
</div>

<div role="navigation">
<ul class="nav nav-tabs">
<% @pages.each do |page| %>
    <li role="presentation" class="<%= @active_page == page ? "active" : "" %>">
        <a href="<%= groups_show_page_url(@group.id, page) %>"><%= page.capitalize %></a>
    </li>
<% end %>
</ul>
</div>

<div class="container">
    <%= render @active_page %>
</div>