config/routes.rb
Rails.application.routes.draw do
    
    root  'sessions#new'

    # Groups
    get '/groups/new'      => 'groups#new',  :as => "groups_new"
    get '/groups/:id/edit' => 'groups#edit', :as => "groups_edit"

    get    '/groups'     => 'groups#index',   :as => "groups_index"
    post   '/groups'     => 'groups#create',  :as => "groups_create"
    get    '/groups/:id' => 'groups#show',    :as => "groups_show"
    patch  '/groups/:id' => 'groups#update',  :as => "groups_update"
    delete '/groups/:id' => 'groups#destroy', :as => "groups_destroy"

    get    '/groups/:id/:page' => 'groups#show',    :as => "groups_show_page"

    # Users
    get '/users/new'      => 'users#new',  :as => "users_new"
    get '/users/:id/edit' => 'users#edit', :as => "users_edit"

    post   '/users'     => 'users#create',  :as => "users_create"
    get    '/users/:id' => 'users#show',    :as => "users_show"
    patch  '/users/:id' => 'users#update',  :as => "users_update"
    delete '/users/:id' => 'users#destroy', :as => "users_destroy"

    # Sessions
    get  '/login'      => 'sessions#new',     :as => "sessions_new"
    post '/sessions'   => 'sessions#create',  :as => "sessions_create"
    delete '/sessions' => 'sessions#destroy', :as => "sessions_destroy"

    # Posts
    post '/posts/:id' => 'posts#create', :as => "posts_create"

    # Photos
    post '/photos/:id' => 'photos#create', :as => "photos_create"
    get  '/photos/:id' => 'photos#show',   :as => "photos_show"

    # Comments
    post '/comments/:id' => 'comments#create', :as => "comments_create"

end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password

    has_many :group_members
    has_many :groups, :through => :group_members
    has_many :photos, :through => :group_members
    has_many :comments

    validates :email, :uniqueness => true, :allow_nil => false
    validates :password, :presence => true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_user, :only => [:show, :edit, :update, :destroy]

    def require_user
        if session[:user_id].blank?
            redirect_to sessions_login_url, notice: "You must be logged in to do that."
        end

        @user = User.find_by(id: session[:user_id])
    end

    def show
    end

    def new
    end

    def create
        user = User.new
        user.first_name = params[:first_name]
        user.last_name = params[:last_name]
        user.email = params[:email]
        user.password = params[:password]

        if user.invalid?
            redirect_to users_new_url, notice: user.errors.messages
            return
        end

        user.save
        session[:user_id] = user.id
        redirect_to groups_index_url
    end

    def edit
    end

    def update
    end

    def destroy
    end

end

app/views/users/new.html.erb
<div class="form-signin">
<%= form_tag users_create_url, :method => 'post', :class => 'form-horizontal' do %>

    <h2 class=form-signin-heading">Create Account</h2>

    <div class="control-group">
    <label for="first_name" class="control-label">First Name</label>
    <input type="text" class="form-control" id="first_name" name="first_name">
</div>

    <label for="last_name" class="control-label">Last Name</label>
    <input type="text" class="form-control" id="last_name" name="last_name">

    <label for="email" class="control-label">Email</label>
    <input type="text" class="form-control" id="email" name="email">

    <label for="password" class="control-label">Password</label>
    <input type="password" class="form-control" id="password" name="password">

    <button type="submit" class="btn btn-default">Create</button>
<% end %>
</div>