config/routes.rb
Rails.application.routes.draw do
    
    root  'sessions#new'

    # Groups
    get '/groups/new'      => 'groups#new',  :as => "groups_new"
    get '/groups/:id/edit' => 'groups#edit', :as => "groups_edit"

    get    '/groups'     => 'groups#index',   :as => "groups_index"
    post   '/groups'     => 'groups#create',  :as => "groups_create"
    get    '/groups/:id' => 'groups#show',    :as => "groups_show"
    patch  '/groups/:id' => 'groups#update',  :as => "groups_update"
    delete '/groups/:id' => 'groups#destroy', :as => "groups_destroy"

    get    '/groups/:id/:page' => 'groups#show',    :as => "groups_show_page"

    # Users
    get '/users/new'      => 'users#new',  :as => "users_new"
    get '/users/:id/edit' => 'users#edit', :as => "users_edit"

    post   '/users'     => 'users#create',  :as => "users_create"
    get    '/users/:id' => 'users#show',    :as => "users_show"
    patch  '/users/:id' => 'users#update',  :as => "users_update"
    delete '/users/:id' => 'users#destroy', :as => "users_destroy"

    # Sessions
    get  '/login'      => 'sessions#new',     :as => "sessions_new"
    post '/sessions'   => 'sessions#create',  :as => "sessions_create"
    delete '/sessions' => 'sessions#destroy', :as => "sessions_destroy"

    # Posts
    post '/posts/:id' => 'posts#create', :as => "posts_create"

    # Photos
    post '/photos/:id' => 'photos#create', :as => "photos_create"
    get  '/photos/:id' => 'photos#show',   :as => "photos_show"

    # Comments
    post '/comments/:id' => 'comments#create', :as => "comments_create"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
  <style>body { padding-top: 70px; }</style>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <% @brand_url = @user ? groups_index_url : sessions_new_url %>
            <a class="navbar-brand" href="<%= @brand_url %>">Group Space</a>
        </div>

        <% if @user != nil %>
        <div class="dropdown navbar-right">
          <a class="navbar-brand navbar-dropdown" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
            <%= @user.first_name + " " + @user.last_name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= sessions_destroy_url %>" data-method='delete'>Log Out</a></li>
          </ul>
        </div>
        <% end %>

    </div>
    </nav>

    <div class="container">

    <% if notice.present? %>
        <div class="alert alert-info"%>
            <%= notice %>
        </div>
    <% end %>

    <%= yield %>
    </div> <!-- /container -->
</body>

</html>